[project]
name = "multiagentrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.2.0",
    "fastmcp>=2.12.5",
    "huggingface>=0.0.1",
    "langchain>=1.0.0",
    "langchain-google-community>=2.0.10",
    "langchain-google-genai>=3.1.0",
    "langchain-huggingface>=1.0.0",
    "langchain-mcp-adapters>=0.1.11",
    "langchain-openai>=1.0.0",
    "langchain-qdrant>=1.1.0",
    "langgraph>=1.0.1",
    "pyyaml>=6.0.3",
    "qdrant-client>=1.15.1",
    "fastapi>=0.115",
    "uvicorn>=0.30",
    "sse-starlette>=2.1",
    "torch==2.9.1",
    "vllm>=0.16.0",
    "langchain-core>=1.0.0",
]
